<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans [
        <!ELEMENT beans (bean)*>
        <!ATTLIST beans
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                autowire CDATA #IMPLIED
                class CDATA #REQUIRED
                id CDATA #REQUIRED
                lazy-init CDATA #IMPLIED>
        <!ELEMENT property (value|ref|list)*>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #IMPLIED>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT ref (#PCDATA)>
        <!ATTLIST ref
                bean CDATA #REQUIRED>
        <!ELEMENT list (ref)*>
        ]>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <!--Test start-->
    <bean id="updateInvoiceInOrderWork" class="com.lenovo.invoice.service.works.UpdateInvoiceInOrderWork">

    </bean>
    <bean id="updateInvoiceInOrderJob" class="org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean">
        <property name="targetObject" ref="updateInvoiceInOrderWork"></property>
        <property name="concurrent">
            <value>false</value>
        </property>
        <property name="targetMethod">
            <value>execute</value>
        </property>
    </bean>

    <bean id="updateInvoiceInOrderTrigger" class="org.springframework.scheduling.quartz.CronTriggerFactoryBean">
        <property name="jobDetail">
            <ref bean="updateInvoiceInOrderJob"/>
        </property>
        <property name="cronExpression">
            <value>0/5 * * * * ?</value>
        </property>
    </bean>
    <!--Test end-->

    <bean id="startQuertz" lazy-init="false" autowire="no"
          class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
        <property name="triggers">
            <list>
                <ref bean="updateInvoiceInOrderTrigger"/>
            </list>
        </property>
    </bean>
</beans>